### ISSUE TITLE
Unable to add user, javascript error

### ISSUE THREAD

**Issue by yaleman** [yeti-platform/yeti#583]
### Description
Unable to add users, get an error in the javascript console.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit bc6d7ab7374f3b015c2f92ed8f5ac7e303f95474
| OS version       | Ubuntu 18.04.4 LTS
| Browser          | Brave Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit), latest Safari

### Steps to Reproduce
1. Followed the installation instructions here: https://yeti-platform.readthedocs.io/en/latest/installation.html
(up to `./yeti.py webserver`) on a fresh Ubuntu 18.04 LTS AMI install on AWS.
2. `apt install -y python3-pip` was required to get pip3 to install requirements
3. Open http://ipaddress:8000/useradmin
4. Click "Add new user" button

#### Expected behavior

Expecting to be able to add a user

#### Actual behavior

Error in javascript console, no response from web application.

```
bootstrap.min.js:6 Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (bootstrap.min.js:6)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at S.fn.init.l [as collapse] (bootstrap.min.js:6)
    at HTMLAnchorElement.<anonymous> (bootstrap.min.js:6)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)
(anonymous) @ bootstrap.min.js:6
each @ jquery.min.js:2
each @ jquery.min.js:2
l @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by yaleman** [comment]
Similarly:

- clicking "logout" (top right) doesn't log me out, takes me back to the main front page as the yeti user

**Comment by bmackalicious** [comment]
Haven't tested, but looks like this is fixed if JQuery is updated to version 3.5.1

Source: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

**Comment by peasead** [comment]
Is there a way to fix this in the Docker image? 

I tried just jumping into the container, ran the update and restarted the container, but that didn't seem to work. `jquery` is at `3.5.1`, but it the "add user" still doesn't do anything.

Steps attempted:
```
docker exec -it dev_yeti_1 /bin/bash
npm install jquery@3.5.1
exit
docker restart dev_yeti_1
npm list jquery
npm WARN deprecated vis@4.20.0: Please consider using https://github.com/visjs
yeti@ /opt/yeti
├─┬ bootstrap-tokenfield@0.12.0
│ └── UNMET DEPENDENCY jquery@2.2.4
├── jquery@3.5.1
└─┬ typeahead.js@0.11.1
  └── jquery@3.5.1  d
```

**Comment by predictiple** [comment]
Upgrading to jquery 3.5.1 resolved this for me (non-docker though). Thanks for the advice @bmackalicious

**Comment by sebdraven** [comment]
thanks for replies !
